### ISSUE TITLE
Implement User Registration

### ISSUE THREAD

**Issue by ReL001** [ReL001/StockPulse#10]
Create a user registration endpoint on the backend
 Implement form validation for user registration data (e.g., username, email, password)
 Store user information securely in the database (hash passwords using bcrypt or similar)
 Implement email verification or account activation process (optional)

**Comment by edsaur** [comment]
Hello! can you assign me this one? 

I want to contribute on putting an user registration using PHP and MySQL.

**Comment by edsaur** [comment]
Hey, thank you! 

Btw, I will work on this task by the weekend. Thank you for assigning me to this task ^^

**Comment by edsaur** [comment]
Hello @ReL001! 

I have implemented this and the Database at PR #17 

Checking it out would be great! God bless you <3

**Comment by edsaur** [comment]
Hello again @ReL001! 

Hey, I didn't realized that you've changed the whole project to an react app... 
I'll try my best to implement the one I've made with react. Thank you again.

**Comment by edsaur** [comment]
I'll review the project in React, and see what I could do. Thanks! <3
